### PR TITLE
Merge develop to main for develop branch removal.

### PR DESCRIPTION
**Pull request by jander-msft**
The `main` branch has been forked to a new `release` branch already. This change merges `develop` to `main` now that all of the pipelines and policies have been updated to trigger on `main` and `release`.

### CODE REVIEW

**Review by WilliamXieMSFT — APPROVED** [review]
:shipit:

**Review by wiktork — APPROVED** [review]

**Comment by wiktork** [comment]
Any chance anything in here introduces new references to develop/main branches?

**Comment by jander-msft** [comment]
> Any chance anything in here introduces new references to the old develop/main branches?

Did a quick search locally and I do not see any old references.

**Pull request merged**
