### PR TITLE
[AppInsights Intercept] Extend API to include all supported parameter counts for `System.Func`

### PR DESCRIPTION
**Pull request by WilliamXieMSFT**

### CODE REVIEW

**Comment by wiktork** [comment]
As far as I can tell, https://github.com/microsoft/InstrumentationEngine-Intercept has dependencies here. Any ideas if these changes will affect them?

**Review by wiktork — APPROVED** [review]

**Comment by WilliamXieMSFT** [comment]
Pending discussions around AppInsights & agent Intercept

**Comment by WilliamXieMSFT** [comment]
Closing this PR as discussions are currently tabled.

**Pull request closed without merging**
