### PR TITLE
Re-include microbuild assets for signing

### PR DESCRIPTION
**Pull request by WilliamXieMSFT**

### CODE REVIEW

**Comment by jander-msft** [comment]
Why is this change being made?

**Comment by WilliamXieMSFT** [comment]
The microbuild package contains props/targets that are needed for signing plugin. Without these imports, our builds were erroring out with 'The target "SignFiles" does not exist in the project'

---
In reply to: [799580867](https://github.com/microsoft/CLRInstrumentationEngine/pull/381#issuecomment-799580867) [](ancestors = 799580867)

**Review by jander-msft — APPROVED** [review]

**Pull request merged**
