### PR TITLE
Change error to message for 'standalone method infos are not configur…

### PR DESCRIPTION
**Pull request by jakubch1**
#323

### CODE REVIEW

**Review by delmyers — APPROVED** [review]

**Comment by delmyers** [comment]
lgtm

closes #323

**Comment by jakubch1** [comment]
@delmyers  please merge it - I don't have rights.

**Comment by delmyers** [comment]
> @delmyers please merge it - I don't have rights.

I was waiting to see if anyone else had comments. I'm fine with it, so I just merged it. Sorry for the delay.

**Pull request merged**
