### PR TITLE
Add testing for ref structs

### PR DESCRIPTION
**Pull request by kkeirstead**
###### Summary 

Adds tests to ensure ref structs support; the changes in this PR were previously reviewed separately in #508, #509, and #516. 

###### Change Log  

- Add ILASM to test project
- Copy ilasm as an embedded resource into the InstrEngineTests assembly
- Add il files to embedded resources
- Refactor the compiler helpers to extract embedded resources as files
- Invoke ilasm to assemble the embedded il
- Removed unused IL code paths (not validating that exceptions are thrown).
- Added C# to exercise the InvalidCSharp IL paths.
- Can assemble multiple IL files together and compile with corresponding C# code.
- Added credits for original InvalidCSharp IL files and C# validation code.
- Added seven baselines/testscripts for validating ref structs
- Integrated Del's fix so that TestAppRunner finds all the needed assemblies (our IL assembly was previously not being added)

###### Test Methodology

The added tests are passing (using baselines generated by a preliminary run of the test).

### CODE REVIEW

**Comment by WilliamXieMSFT** [comment]
Mind updating the Changelog.md?

**Review by WilliamXieMSFT — APPROVED** [review]

**Comment by delmyers** [comment]
FYI, for future reference, it is best practice to squash each PR when you merge it into a branch. This PR should only have 3-4 commits, but it has 40 because your last PR wasn't squashed.

Normally, we merge in feature branches, and squash PRs. Github does it for you when you submit your PR.

Please just merge this PR into main, though (don't squash it).

**Comment by delmyers** [comment]
:shipit:

**Review by delmyers — APPROVED** [review]

**Comment by delmyers** [comment]
@WilliamXieMSFT Yeah, it is fine to leave the policy the way it is. I don't think we want to squash merge everything. In my mind, it makes sense to keep RI/FI history so that when feature branches are merged into main, or main is merged into feature branches, we keep the original history. The thing that makes sense to squash is individual PRs.

**Pull request merged**
